### ISSUE TITLE
align.h file missing

### ISSUE THREAD

**Issue by Roboterbastler** [gondsm/mrgs#1]
Hi Gonçalo,

while trying to get your mrgs_alignment code running I noticed that the file align.h needed by align_node.cpp and align_test.cpp seems to be missing in the repository, is that right?. Is there a chance you add it?

Best regards,
Jacob

**Comment by gondsm** [comment]
Hey Jacob,

Thank you for your interest!

I remember deploying this to several machines and compiling without issues, so I find this issue strange. I'll look into this and come back to you as soon as possible. 

Anyway, the original mapmerge package (which I'm reusing) can be found here:
http://robotics.ucmerced.edu/map-merging-code (first download link).

Regards,
Gonçalo.

**Comment by Roboterbastler** [comment]
Thank your for the very quick response!
I already found the package you link, but as I'm interested in using standard ROS message types like OccupancyGrid (as your package does) your package is more appealing to me.

Jacob

**Comment by gondsm** [comment]
Perhaps I wasn't clear: the package I linked is the basis on which I built the mrgs_alignment node. As such, it should contain the align.h file you need, which you should be able to use while I figure this issue out ;)

**Comment by Roboterbastler** [comment]
No, unfortunately it doesn't contain such a file. And I can build the library 'mapmerge' without problems. Just when building mrgs_alignment this line causes the problem: https://github.com/gondsm/mrgs/blob/master/mrgs_alignment/src/align_node.cpp#L62

**Comment by gondsm** [comment]
I see. Well, in that case, I'll need some time to figure this out since, at the moment, I don't even have a build environment capable of building this system. I assure you I'll find a solution!

**Comment by gondsm** [comment]
So, I've checked and align.h is a build artifact generated somewhere during compilation (it's found in the devel folder upon compilation).

What version of ROS are you using? Is this the only package you're compiling?

**Comment by Roboterbastler** [comment]
I'm using Indigo and therefore I edited the files in order to build it with catkin_make, in this case there might be the problem...

**Comment by gondsm** [comment]
As long as you respect the dependencies (some packages need each other's messages, but I do not think that is the case), then you should be okay building them separately.

Yes, the fact that you are using a catkin ROS distro must be the problem. We have a catkinized version of this package here at the lab, but I'm not at liberty to share it yet! Give me some time.

**Comment by Roboterbastler** [comment]
Okay, I'll try to figure out a way otherwise I'll go with the original mapmerge package.

Thanks again! :)

**Comment by gondsm** [comment]
You're welcome! In the meantime I'll see if/when I might be able to publish the newer version.

Anyway, it should be a matter of editing the CMakelists.txt. I'm closing this issue, since it doesn't really apply, but feel free to contact me again if you need any more assistance!
